Lab_1
SmetskayaAnast/Programming-Methods pull request #4
Opened 2024-02-23 13:24 UTC by SmetskayaAnast

2024-02-25 18:21 UTC, FlashAnton requested changes
Здравствуйте.

А, всё же, ссылки оформляются как-то так:
![image](https://github.com/SmetskayaAnast/Programming-Methods/assets/95698986/0c30e217-98ad-49ba-ae13-070cbb29e47b)

Должно быть отчётливое понимание, какая именно метка и куда ведёт:
![image](https://github.com/SmetskayaAnast/Programming-Methods/assets/95698986/eb227f2c-8817-482f-8e07-0566b1ef5dba)

Одну ссылку по смене устойчивого состояния Вы сделали почти правильно, но на ней не хватает метки. Это касается, в том числе, и краткой сети. Там, конечно, интуитивно понятна связь, но должно быть не интуитивно, а чётко.

2024-02-29 15:29 UTC, SmetskayaAnast commented
[1_lab_Автоношкин_Смецкая(Ссылки).docx](https://github.com/SmetskayaAnast/Programming-Methods/files/14450053/1_lab_._.docx)

2024-03-05 18:47 UTC, FlashAnton requested changes
По ветке "Lab1" размещено совершенно не то, что я видел на Вашем ноутбуке в Университете.

Возможно, оно попало в "Lab2" - буду смотреть.
Эта ветка в нынешнем её состоянии одобрения не получает.

2024-03-05 19:43 UTC, FlashAnton approved these changes
Вот так бы сразу.
Теперь наблюдаю именно ту версию, которой дал зелёный свет.
**Зачтено**

2024-03-05 19:43 UTC, merged